// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjQr2SDG5MBce8aRrfxjzeLe0MCp9w90I',
    appId: '1:509832403396:web:86927e5ac4f5ac091fec91',
    messagingSenderId: '509832403396',
    projectId: 'mlapps-ea4ea',
    authDomain: 'mlapps-ea4ea.firebaseapp.com',
    storageBucket: 'mlapps-ea4ea.appspot.com',
    measurementId: 'G-67XBY3ZTC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZqNgK5nZaRIdtmyLHF8CgJZEiGfp5Umc',
    appId: '1:509832403396:android:4f7e8f338087278e1fec91',
    messagingSenderId: '509832403396',
    projectId: 'mlapps-ea4ea',
    storageBucket: 'mlapps-ea4ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDJ8cADRDJTOPOrMJb697Wp-6kxC6DmAs',
    appId: '1:509832403396:ios:b584864eedef7cb51fec91',
    messagingSenderId: '509832403396',
    projectId: 'mlapps-ea4ea',
    storageBucket: 'mlapps-ea4ea.appspot.com',
    androidClientId: '509832403396-1nq13rmfu78clfo343bnbjcl64194c0t.apps.googleusercontent.com',
    iosClientId: '509832403396-nig3p71hiokmfdsko0h5ktk3iepimpv5.apps.googleusercontent.com',
    iosBundleId: 'com.darckly.prestamos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDJ8cADRDJTOPOrMJb697Wp-6kxC6DmAs',
    appId: '1:509832403396:ios:b584864eedef7cb51fec91',
    messagingSenderId: '509832403396',
    projectId: 'mlapps-ea4ea',
    storageBucket: 'mlapps-ea4ea.appspot.com',
    androidClientId: '509832403396-1nq13rmfu78clfo343bnbjcl64194c0t.apps.googleusercontent.com',
    iosClientId: '509832403396-nig3p71hiokmfdsko0h5ktk3iepimpv5.apps.googleusercontent.com',
    iosBundleId: 'com.darckly.prestamos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjQr2SDG5MBce8aRrfxjzeLe0MCp9w90I',
    appId: '1:509832403396:web:7ac7171c56a33a891fec91',
    messagingSenderId: '509832403396',
    projectId: 'mlapps-ea4ea',
    authDomain: 'mlapps-ea4ea.firebaseapp.com',
    storageBucket: 'mlapps-ea4ea.appspot.com',
    measurementId: 'G-FDJMHY7NBP',
  );
}
